#!/bin/sh
xsetroot -solid black &

# keyboard settings
xset r rate 400 90 &
setxkbmap -layout "us" -variant "altgr-intl" -option "shift:both_capslock" && xmodmap .Xmodmap 

# touchpad settings
sh .touchpad-settings &

# fonts
xset +fp /usr/local/share/fonts/terminus/ +fp /usr/local/share/fonts/Droid/ &

uxterm &

# status: hardware info and date
while true
do
	xsetroot -name "`hwinfo` | `date +"%a %e %b %H:%M"`"
	sleep 30
done &
exec dwm
